app/invoices/routes.py
import datetime
from datetime import date

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.invoices.forms import FilterForm, InvoiceForm, ItemForm
from app.models import Company, Invoice, InvoiceType, Item, Roles
from app.utils import roles_required

invoices = Blueprint('invoices', __name__)


@invoices.route('/invoice/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def create_invoice():
    form = InvoiceForm()

    if request.method == 'GET':
        form.issue_date.data = date.today()  # .strftime('%Y-%m-%d')
        form.due_date.data = date.today()

    if form.validate_on_submit():
        company = Company.query.get_or_404(1)  # we have only one company (id 1)
        new_invoice = Invoice(issue_date=form.issue_date.data,
                              due_date=form.due_date.data,
                              payment_form=form.payment_form.data,
                              type=form.type.data,
                              invoice_buyer=form.buyer.data,
                              invoice_author=current_user,
                              invoice_company=company)
        new_invoice.create_serial_number()
        db.session.add(new_invoice)

        total_sum = 0
        for item in form.items.data:
            new_item = Item(**item)
            new_item.total_price = new_item.count * new_item.price
            total_sum += new_item.total_price
            db.session.add(new_item)
            new_invoice.items.append(new_item)

        new_invoice.total_sum = total_sum
        db.session.commit()
        flash('Your invoice has been created!', 'success')
        return redirect(url_for('invoices.invoice', invoice_id=new_invoice.id))

    return render_template('create_invoice.html', title='Create Invoice', form=form)


@invoices.route('/invoice/<int:invoice_id>', methods=['GET'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def invoice(invoice_id):
    """Show the details of a invoice"""
    bill = Invoice.query.get_or_404(invoice_id)
    return render_template('invoice.html', invoice=bill)


@invoices.route('/invoice', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def search_invoices():
    search = FilterForm()
    if request.method == 'POST':
        return list_invoices()
    return render_template('search_invoices.html', filter=search)


@invoices.route('/invoice/search', methods=['POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def list_invoices():
    def _filter(q, it):
        """Filter Query by Invoice Type.

        :param q: SQLAlchemy Query
        :param it: Invoice Type
        :return: List of Invoices in the filtered Query
        """
        if it == InvoiceType.All.value[0]:  # it == 'All'
            q = q.order_by(Invoice.id.desc())
        else:
            q = q.filter(Invoice.type == it) \
                .order_by(Invoice.id.desc())
        return q.all()

    search = request.form

    date_from = search['date_from']
    date_till = search['date_till']

    if date_from:
        date_from = datetime.datetime.strptime(search['date_from'], '%Y-%m-%d')
    if date_till:
        date_till = datetime.datetime.strptime(search['date_till'], '%Y-%m-%d')
    invoice_type = int(search['invoice_type'])

    query = Invoice.query

    if not date_from and not date_till:  # no dates
        results = _filter(query, invoice_type)
    elif date_from and not date_till:  # date_from only
        query = query.filter(date_from <= Invoice.issue_date)
        results = _filter(query, invoice_type)
    elif not date_from and date_till:  # date_till only
        query = query.filter(date_till <= Invoice.issue_date)
        results = _filter(query, invoice_type)
    else:  # both dates
        query = query \
            .filter(date_from <= Invoice.issue_date) \
            .filter(date_till >= Invoice.issue_date)
        results = _filter(query, invoice_type)

    if not results:
        flash('No results found!', 'warning')
        return redirect(url_for('invoices.search_invoices'))
    else:
        # display results
        return render_template('list_invoices.html', invoices=results)


@invoices.route('/invoice/<int:invoice_id>/update', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def update_invoice(invoice_id):
    current_invoice: Invoice = Invoice.query.get_or_404(invoice_id)
    form = InvoiceForm(request.form)
    if form.validate_on_submit():
        current_invoice.issue_date = form.issue_date.data
        current_invoice.due_date = form.due_date.data
        current_invoice.payment_form = form.payment_form.data
        current_invoice.type = form.type.data
        current_invoice.invoice_buyer = form.buyer.data

        for item in current_invoice.items:
            Item.query.filter_by(id=item.id).delete()

        total_sum = 0
        for item in form.items.data:
            new_item = Item(**item)
            new_item.total_price = new_item.count * new_item.price
            total_sum += new_item.total_price
            db.session.add(new_item)
            current_invoice.items.append(new_item)

        current_invoice.total_sum = total_sum

        db.session.commit()
        flash('Your invoice has been updated!', 'success')
        return redirect(url_for('invoices.invoice', invoice_id=invoice_id))
    elif request.method == 'GET':
        form.issue_date.data = current_invoice.issue_date
        form.due_date.data = current_invoice.due_date
        form.payment_form.data = current_invoice.payment_form
        form.type.data = current_invoice.type
        form.buyer.data = current_invoice.invoice_buyer

        current_item: Item
        for current_item in current_invoice.items:
            item = ItemForm()
            item.desc = current_item.desc
            item.count = current_item.count
            item.price = current_item.price
            item.unit = current_item.unit
            item.vat = current_item.vat

            form.items.append_entry(item)

    return render_template('create_invoice.html', title='Update Invoice', form=form)


@invoices.route('/invoice/<int:invoice_id>/delete', methods=['POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def delete_invoice(invoice_id):
    bill = Invoice.query.get_or_404(invoice_id)
    db.session.delete(bill)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('invoices.search_invoices'))

app/main/routes.py
import os

from flask import Blueprint, render_template, request, send_from_directory, current_app

from app.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', default=1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static'),
                               'favicon.ico',
                               mimetype='image/vnd.microsoft.icon')

app/posts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.models import Post, Roles
from app.posts.forms import PostForm
from app.utils import roles_required

posts = Blueprint('posts', __name__)


@posts.route('/post/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, post_author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.post_author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.post_author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

app/users/routes.py
from typing import List

from faker import Faker
from faker.providers import barcode, internet, phone_number, credit_card
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from app import bcrypt, db
from app.models import Role, Roles, User
from app.users.forms import (LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm,
                             UpdateUserForm)
from app.users.utils import save_picture, send_reset_email
from app.utils import roles_required

from random import randint

users = Blueprint('users', __name__)

fake = Faker()
fake.add_provider(barcode)
fake.add_provider(internet)
fake.add_provider(phone_number)
fake.add_provider(credit_card)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check username and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token!', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/user')
@login_required
@roles_required([Roles.ADMIN.value])
def list_users():
    users: List = User.query.order_by(User.username.asc()).all()
    users.remove(current_user)  # remove current user from the list
    return render_template('list_users.html', users=users)


# noinspection PyArgumentList
@users.route('/user/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def create_user():
    form = RegistrationForm()

    if request.method == 'GET':
        # push random values into the form
        form.name.data = fake.name()
        form.birth_number.data = fake.ean(length=13)
        form.address.data = fake.address()
        form.username.data = 'User' + str(randint(1000, 9999))
        form.email.data = form.username.data + '@' + fake.free_email_domain()
        form.phone.data = fake.phone_number()
        form.card_number.data = fake.credit_card_number(card_type=None)
        form.account_number.data = fake.ean(length=13)
        form.password.data = str(randint(1000, 9999))

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user_role = Role.query.filter_by(name=form.role.data).first()
        user = User(name=form.name.data,
                    birth_number=form.birth_number.data,
                    address=form.address.data,
                    username=form.username.data,
                    email=form.email.data,
                    phone=form.phone.data,
                    card_number=form.card_number.data,
                    account_number=form.account_number.data,
                    password=hashed_password,
                    role_id=user_role.id)
        db.session.add(user)
        db.session.commit()
        flash(f'The account has been created! User is now able to log in.', 'success')
        return redirect(url_for('users.list_users'))
    return render_template('create_user.html', title='Register', form=form)


@users.route('/user/<int:user_id>/update', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def update_user(user_id):
    user = User.query.get_or_404(user_id)
    form = UpdateUserForm()
    form.id.data = user.id  # we need to push user id into the form to validate user uniqueness
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            user.image_file = picture_file
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash(f'The account of user {user.username} has been updated!', 'success')
        return redirect(url_for('users.update_user', user_id=user.id))
    elif request.method == 'GET':
        form.username.data = user.username
        form.email.data = user.email
    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    return render_template('update_user.html', title='User', image_file=image_file, form=form, user=user)


@users.route('/user/<int:user_id>/delete', methods=['POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.list_users'))

app/templates/partials/contact_overview.html
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{{ url_for('companies.contact', contact_id=contact.id) }}">{{ contact.name }}</a></h2>
    </div>
</article>

app/templates/partials/contact_ud_view.html
<div class="article-metadata">
    <div>
        <a class="btn btn-primary" href="{{ url_for('companies.update_contact', contact_id=contact.id) }}">Update</a>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" id="deleteConfirm"
                onclick="deleteConfirmPost()">Delete
        </button>

        <!-- Modal -->
        <script>
            function deleteConfirmPost() {
                const form = document.createElement('form');
                form.method = "post";
                form.action = "{{ url_for('companies.delete_contact', contact_id=contact.id) }}";

                if (confirm("Delete Contact?") === true) {
                    document.body.appendChild(form);
                    form.submit();
                }
            }
        </script>
    </div>
</div>

app/templates/partials/form_template.html
<div id="item-_-form" class="subform hidden" data-index="0">
    <!-- Count -->
    <div class="form-group">
        <label class="form-control-label" for="items-_-count">Count</label>
        <input class="form-control form-control-lg" id="items-_-count" name="items-_-count"
               required="" type="text" value="">
    </div>

    <!-- Unit -->
    <div class="form-group">
        <label class="form-control-label" for="items-_-unit">Unit</label>
        <input class="form-control form-control-lg" id="items-_-unit" name="items-_-unit"
               required="" type="text" value="">
    </div>

    <!-- Description -->
    <div class="form-group">
        <label class="form-control-label" for="items-_-desc">Description</label>
        <input class="form-control form-control-lg" id="items-_-desc" name="items-_-desc"
               required="" type="text" value="">
    </div>

    <!-- VAT Rate -->
    <div class="form-group">
        <label class="form-control-label" for="items-_-vat">VAT</label>
        <input class="form-control form-control-lg" id="items-_-vat" name="items-_-vat" required=""
               type="text" value="">
    </div>

    <!-- Price -->
    <div class="form-group">
        <label class="form-control-label" for="items-_-price">Price</label>
        <input class="form-control form-control-lg" id="items-_-price" name="items-_-price"
               required="" type="text" value="">
    </div>

    <!-- Remove Item Button -->
    <a class="remove btn btn-danger" href="#" role="button">Remove</a>
</div>

app/templates/partials/invoice_overview.html
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{{ url_for('invoices.invoice', invoice_id=invoice.id) }}">{{ invoice.serial_number }}</a></h2>
        <div class="group">
            <span class="info">Date Created: {{ invoice.date_created }}</span>
            <span class="info">Issue Date: {{ invoice.issue_date }}</span>
            <span class="info last">Due Date: {{ invoice.due_date }}</span>
        </div>
    </div>
</article>

app/templates/partials/invoice_ud_view.html
<div class="article-metadata">
    <div>
        <a class="btn btn-primary" href="{{ url_for('invoices.update_invoice', invoice_id=invoice.id) }}">Update</a>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" id="deleteConfirm"
                onclick="deleteConfirmPost()">Delete
        </button>

        <!-- Modal -->
        <script>
            function deleteConfirmPost() {
                const form = document.createElement('form');
                form.method = "post";
                form.action = "{{ url_for('invoices.delete_invoice', invoice_id=invoice.id) }}";

                if (confirm("Delete Invoice?") === true) {
                    document.body.appendChild(form);
                    form.submit();
                }
            }
        </script>
    </div>
</div>

app/templates/partials/navigation.html
<header class="site-header">
    <nav class="navbar">
        <div class="container">
            <ul class="navbar-list">
                <li class="navbar-item">
                    <a class="navbar-link" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" href="{{ url_for('companies.company') }}">Company</a>
                </li>

                {% if current_user.is_authenticated %}

                    {% if current_user.is_admin() %}
                        <li class="navbar-item">
                            <a class="navbar-link" href="{{ url_for('users.list_users') }}">Users</a>
                        </li>
                    {% elif not current_user.is_admin() %}
                        <li class="navbar-item">
                            <a class="navbar-link" href="{{ url_for('invoices.search_invoices') }}">Invoices</a>
                        </li>
                        <li class="navbar-item">
                            <a class="navbar-link" href="{{ url_for('companies.list_contacts') }}">Contacts</a>
                        </li>
                    {% endif %}

                    <li class="navbar-item">
                        <a class="navbar-link" href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="navbar-item">
                        <a class="navbar-link" href="{{ url_for('users.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="navbar-item">
                        <a class="navbar-link" href="{{ url_for('users.login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</header>

app/templates/partials/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

        {% if posts.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('main.home', page=posts.prev_num) }}" tabindex="-1" aria-disabled="true">
                    Previous
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if page_num %}
                {% if posts.page == page_num %}
                    <li class="page-item active">
                        <a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-disabled="true">
                        <span class=ellipsis>…</span>
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('main.home', page=posts.next_num) }}" tabindex="-1" aria-disabled="true">
                    Next
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>

app/templates/partials/post_overview.html
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content | truncate(150)}}</p>
    </div>
</article>

app/templates/partials/post_ud_view.html
<div class="article-metadata">
    {% if post.post_author == current_user %}
        <div>
            <a class="btn btn-primary" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" id="deleteConfirm"
                    onclick="deleteConfirmPost()">Delete
            </button>

            <!-- Modal -->
            <script>
                function deleteConfirmPost() {
                    const form = document.createElement('form');
                    form.method = "post";
                    form.action = "{{ url_for('posts.delete_post', post_id=post.id) }}";

                    if (confirm("Delete Post?") === true) {
                        document.body.appendChild(form);
                        form.submit();
                    }
                }
            </script>

        </div>
    {% endif %}
</div>

app/templates/partials/user_overview.html
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{{ url_for('users.update_user', user_id=user.id) }}">{{ user.username }}</a></h2>
        <p class="article-content">E-Mail: {{ user.email }}</p>
        <p class="article-content">Password: {{ user.password | truncate(30) }}</p>
    </div>
</article>