app/companies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    name = StringField('Name', validators=[
        DataRequired()
    ])
    residence = StringField('Residence', validators=[
        DataRequired()
    ])
    ic = StringField('IČ', validators=[
        DataRequired()
    ])
    dic = StringField('DIČ', validators=[
        DataRequired()
    ])
    phone = StringField('Phone Number', validators=[
        DataRequired()
    ])
    email = StringField('Email', validators=[
        DataRequired(),
        Email()
    ])
    submit = SubmitField('Submit')

app/invoices/forms.py
from flask_wtf import FlaskForm
from wtforms import FieldList, FloatField, Form, FormField, IntegerField, SelectField, StringField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired

from app.models import Contact, InvoiceType, Payment


class FilterForm(FlaskForm):
    """Invoices filter form"""
    date_from = DateField('Issue Date From')
    date_till = DateField('Issue Date Till')
    invoice_type = SelectField('Invoice Type', choices=[item.value for item in InvoiceType])
    submit = SubmitField('Filter View', )


class ItemForm(Form):
    """Invoices subform

    CSRF is disabled for this subform (using `Form` as parent class) because it is never used by itself.
    """
    count = FloatField('Count', default=0.0)
    unit = StringField('Unit', validators=[
        DataRequired()
    ])
    desc = StringField('Description', validators=[
        DataRequired()
    ])
    vat = IntegerField('VAT', default=0)
    price = FloatField('Price', default=0.0)


class InvoiceForm(FlaskForm):
    issue_date = DateField('Date of Issue', validators=[
        DataRequired()
    ])
    due_date = DateField('Date of Taxable Supply', validators=[
        DataRequired()
    ])
    payment_form = SelectField('Form of Payment', coerce=int, choices=[item.value for item in Payment])
    type = SelectField('Invoice Type', coerce=int, choices=[InvoiceType.Inbound.value,
                                                            InvoiceType.Outbound.value])
    buyer = QuerySelectField('Buyer', query_factory=lambda: Contact.query.all(), get_label='name')
    items = FieldList(FormField(ItemForm))

    submit = SubmitField('Submit')

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[
        DataRequired()
    ])
    content = TextAreaField('Content', validators=[
        DataRequired()
    ])
    submit = SubmitField('Post')

app/companies/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required

from app import db
from app.models import Company, Contact, Roles
from app.utils import roles_required
from app.companies.forms import ContactForm

companies = Blueprint('companies', __name__)


@companies.route('/contact', methods=['GET'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def list_contacts():
    page = request.args.get('page', default=1, type=int)
    contacts = Contact.query.order_by(Contact.name.asc()).paginate(page=page, per_page=5)
    return render_template('list_contacts.html', contacts=contacts)


@companies.route('/contact/<int:contact_id>', methods=['GET'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def contact(contact_id):
    cont = Contact.query.get_or_404(contact_id)
    return render_template('contact.html', contact=cont)


@companies.route('/contact/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def create_contact():
    form = ContactForm()
    if form.validate_on_submit():
        comp = Company.query.get_or_404(1)
        new_contact = Contact(name=form.name.data,
                              residence=form.residence.data,
                              ic=form.ic.data,
                              dic=form.dic.data,
                              phone=form.phone.data,
                              email=form.email.data,
                              contact_author=comp)
        db.session.add(new_contact)
        db.session.commit()
        flash('Your contact has been created!', 'success')
        return redirect(url_for('companies.contact', contact_id=new_contact.id))
    return render_template('create_contact.html', title='Create Contact', form=form)


@companies.route('/contact/<int:contact_id>/delete', methods=['POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def delete_contact(contact_id):
    cont = Contact.query.get_or_404(contact_id)
    db.session.delete(cont)
    db.session.commit()
    flash('Your contact has been deleted!', 'success')
    return redirect(url_for('companies.list_contacts'))


@companies.route('/contact/<int:contact_id>/update', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ACCOUNTANT.value])
def update_contact(contact_id):
    current_contact: Contact = Contact.query.get_or_404(contact_id)
    form = ContactForm()
    if form.validate_on_submit():
        current_contact.name = form.name.data
        current_contact.residence = form.residence.data
        current_contact.dic = form.dic.data
        current_contact.ic = form.ic.data
        current_contact.email = form.email.data
        current_contact.phone = form.phone.data

        db.session.commit()
        flash('Your contact has been updated!', 'success')
        return redirect(url_for('companies.contact', contact_id=current_contact.id))
    elif request.method == 'GET':
        form.name.data = current_contact.name
        form.residence.data = current_contact.residence
        form.dic.data = current_contact.dic
        form.ic.data = current_contact.ic
        form.email.data = current_contact.email
        form.phone.data = current_contact.phone
    return render_template('create_contact.html', title='Update Contact', form=form)


@companies.route('/company', methods=['GET'])
def company(company_id=1):
    comp = Company.query.get_or_404(company_id)
    return render_template('company.html', company=comp)

app/posts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.models import Post, Roles
from app.posts.forms import PostForm
from app.utils import roles_required

posts = Blueprint('posts', __name__)


@posts.route('/post/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, post_author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.post_author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.post_author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

app/users/routes.py
from typing import List

from faker import Faker
from faker.providers import barcode, internet, phone_number, credit_card
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from app import bcrypt, db
from app.models import Role, Roles, User
from app.users.forms import (LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm,
                             UpdateUserForm)
from app.users.utils import save_picture, send_reset_email
from app.utils import roles_required

from random import randint

users = Blueprint('users', __name__)

fake = Faker()
fake.add_provider(barcode)
fake.add_provider(internet)
fake.add_provider(phone_number)
fake.add_provider(credit_card)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check username and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token!', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/user')
@login_required
@roles_required([Roles.ADMIN.value])
def list_users():
    users: List = User.query.order_by(User.username.asc()).all()
    users.remove(current_user)  # remove current user from the list
    return render_template('list_users.html', users=users)


# noinspection PyArgumentList
@users.route('/user/create', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def create_user():
    form = RegistrationForm()

    if request.method == 'GET':
        # push random values into the form
        form.name.data = fake.name()
        form.birth_number.data = fake.ean(length=13)
        form.address.data = fake.address()
        form.username.data = 'User' + str(randint(1000, 9999))
        form.email.data = form.username.data + '@' + fake.free_email_domain()
        form.phone.data = fake.phone_number()
        form.card_number.data = fake.credit_card_number(card_type=None)
        form.account_number.data = fake.ean(length=13)
        form.password.data = str(randint(1000, 9999))

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user_role = Role.query.filter_by(name=form.role.data).first()
        user = User(name=form.name.data,
                    birth_number=form.birth_number.data,
                    address=form.address.data,
                    username=form.username.data,
                    email=form.email.data,
                    phone=form.phone.data,
                    card_number=form.card_number.data,
                    account_number=form.account_number.data,
                    password=hashed_password,
                    role_id=user_role.id)
        db.session.add(user)
        db.session.commit()
        flash(f'The account has been created! User is now able to log in.', 'success')
        return redirect(url_for('users.list_users'))
    return render_template('create_user.html', title='Register', form=form)


@users.route('/user/<int:user_id>/update', methods=['GET', 'POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def update_user(user_id):
    user = User.query.get_or_404(user_id)
    form = UpdateUserForm()
    form.id.data = user.id  # we need to push user id into the form to validate user uniqueness
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            user.image_file = picture_file
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash(f'The account of user {user.username} has been updated!', 'success')
        return redirect(url_for('users.update_user', user_id=user.id))
    elif request.method == 'GET':
        form.username.data = user.username
        form.email.data = user.email
    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    return render_template('update_user.html', title='User', image_file=image_file, form=form, user=user)


@users.route('/user/<int:user_id>/delete', methods=['POST'])
@login_required
@roles_required([Roles.ADMIN.value])
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.list_users'))

app/templates/account.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="account-img" src="{{ image_file }}" alt="Profile picture">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <form method="post" action="" enctype="multipart/form-data">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>

                <!-- Username -->
                {{ render_field(form.username) }}

                <!-- Email -->
                {{ render_field(form.email) }}

                <!-- Picture -->
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-default") }}
            </div>

        </form>

    </div>
{% endblock content %}

app/templates/company.html
{% extends 'blocks/base.html' %}

{% block content %}
    <article class="media content-section">
        <div class="media-body">

            <h2 class="article-title">Company Credentials</h2>

            <div class="group">
                <span class="info">
                    <b>Name:</b> {{ company.name }}
                </span>
                <span class="info">
                    <b>DIČ:</b> {{ company.dic }}
                </span>
                <span class="info last">
                    <b>Residence:</b> {{ company.residence }}
                </span>
            </div>
        </div>
    </article>
{% endblock content %}

app/templates/contact.html
{% extends 'blocks/base.html' %}

{% block content %}
    <article class="media content-section">
        <div class="media-body">

            {% include 'partials/contact_ud_view.html' %}

            <h2 class="article-title">{{ contact.name }}</h2>

            <div class="group">
                <span class="info">
                    <b>DIČ:</b> {{ contact.dic }}
                </span>
                <span class="info">
                    <b>IČ:</b> {{ contact.dic }}
                </span>
                <span class="info">
                    <b>Residence:</b> {{ contact.residence }}
                </span>
                <span class="info">
                    <b>Phone:</b> {{ contact.phone }}
                </span>
                <span class="info last">
                    <b>Email:</b> {{ contact.email }}
                </span>
            </div>

        </div>
    </article>
{% endblock content %}

app/templates/create_contact.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">

        <form id="invoice-form" method="post" action="" role="form">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <h2>{{ title }}</h2>

            <fieldset class="form-group">
                {{ render_field(form.name) }}
                {{ render_field(form.residence) }}
                {{ render_field(form.ic) }}
                {{ render_field(form.dic) }}
                {{ render_field(form.phone) }}
                {{ render_field(form.email) }}
            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>

        </form>

    </div>

{% endblock %}

app/templates/create_invoice.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">

        {# Form Template #}
        {% include 'partials/form_template.html' %}

        <form id="invoice-form" method="post" action="" role="form">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <h2>{{ title }}</h2>

            <fieldset class="form-group">
                <!-- Date Created -->
                {{ render_field(form.issue_date) }}

                <!-- Due Date -->
                {{ render_field(form.due_date) }}

                <!-- Payment -->
                {{ render_field(form.payment_form) }}

                <!-- Invoice Type -->
                {{ render_field(form.type) }}

                <!-- Buyer -->
                {{ render_field(form.buyer) }}

                <!-- Add Item Button -->
                <a id="add" href="#" class="btn btn-primary" role="button">Add Item</a>

                <!-- Items -->
                <div id="subforms-container">

                    {% for subform in form.items %}
                        <div id="item-{{ loop.index0 }}-form" class="subform" data-index="{{ loop.index0 }}">

                            <!-- Count -->
                            {{ render_field(subform.count) }}

                            <!-- Unit -->
                            {{ render_field(subform.unit) }}

                            <!-- Description -->
                            {{ render_field(subform.desc) }}

                            <!-- VAT Rate -->
                            {{ render_field(subform.vat) }}

                            <!-- Price -->
                            {{ render_field(subform.price) }}

                            <!-- Remove Item Button -->
                            <a class="remove btn btn-danger" href="#" role="button">Remove</a>

                        </div>
                    {% endfor %}
                </div>

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>

        </form>

    </div>

    <script type="text/javascript" src="{{ url_for('static', filename='js/invoice.js') }}"></script>

{% endblock %}

app/templates/create_post.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>

                <!-- Title -->
                {{ render_field(form.title) }}

                <!-- Content -->
                {{ render_field(form.content) }}

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>

        </form>
    </div>
{% endblock %}

app/templates/create_user.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="legend">Create New User</legend>

                <!-- Name -->
                {{ render_field(form.name) }}

                <!-- Birth Number -->
                {{ render_field(form.birth_number) }}

                <!-- Address -->
                {{ render_field(form.address) }}

                <!-- Email -->
                {{ render_field(form.email) }}

                <!-- Phone Number -->
                {{ render_field(form.phone) }}

                <!-- Card Number -->
                {{ render_field(form.card_number) }}

                <!-- Account Number -->
                {{ render_field(form.account_number) }}

                <!-- Username -->
                {{ render_field(form.username) }}

                <!-- Password -->
                {{ render_field(form.password) }}

                <!-- ReCAPTCHA -->
                {{ render_field(form.recaptcha) }}

                <!-- Role -->
                {{ render_field(form.role) }}

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-default") }}
            </div>

        </form>
    </div>
{% endblock content %}

app/templates/home.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_pagination %}

{% block content %}

    {% if current_user.is_authenticated %}
        {% if current_user.is_admin() %}
            <div class="last">
                <a class="btn btn-primary" href="{{ url_for('posts.create_post') }}">New Post</a>
            </div>
        {% endif %}
    {% endif %}

    {% for post in posts.items %}
        {% include 'partials/post_overview.html' %}
    {% endfor %}

    {{ render_pagination(posts, 'main.home') }}

{% endblock content %}

app/templates/list_contacts.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_pagination %}

{% block content %}

    <h1>Contacts</h1>

    <div class="last">
        <a class="btn btn-primary" href="{{ url_for('companies.create_contact') }}">New Contact</a>
    </div>

    {% for contact in contacts.items %}
        {% include 'partials/contact_overview.html' %}
    {% endfor %}

    {{ render_pagination(contacts, 'companies.list_contacts') }}

{% endblock content %}

app/templates/list_invoices.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}

    <h1>Invoices</h1>

    {% for invoice in invoices %}
        {% include 'partials/invoice_overview.html' %}
    {% endfor %}

{% endblock content %}

app/templates/list_users.html
{% extends 'blocks/base.html' %}

{% block content %}

    <h1>List of Users</h1>

    <div class="last">
        <a class="btn btn-primary" href="{{ url_for('users.create_user') }}">Create New User</a>
    </div>

    {% for user in users %}
        {% include 'partials/user_overview.html' %}
    {% endfor %}

{% endblock content %}

app/templates/post.html
{% extends 'blocks/base.html' %}

{% block content %}
    <article class="media content-section">
        <div class="media-body">

            {% include 'partials/post_ud_view.html' %}

            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
{% endblock content %}

app/templates/reset_request.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                <!-- Email -->
                {{ render_field(form.email) }}

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-default") }}
            </div>

        </form>
    </div>
{% endblock content %}

app/templates/reset_token.html
{% extends 'blocks/base.html' %}

{% from "macros/macros.html" import render_field %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            <!-- csrf token -->
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                <!-- Password -->
                {{ render_field(form.password) }}

                <!-- Confirm Password -->
                {{ render_field(form.confirm_password) }}

            </fieldset>

            <!-- Submit Button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-default") }}
            </div>

        </form>
    </div>
{% endblock content %}